import type { Link } from '../src/types.ts'
import type { LinkFile } from './validate-links.ts'
// Compiles links/*.json into src/links.generated.ts: a map of slug -> link, imported
// by the Worker so every redirect is served from the bundle with zero KV reads at
// runtime (D3). The generated file is gitignored and rebuilt on every deploy, so git
// holds one copy of the truth (the JSON files). Reuses readLinkFiles rather than
// re-reading the directory. Runs with plain `node` (no build step), same as
// validate-links.ts.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { readLinkFiles, validateLinkFiles } from './validate-links.ts'

/**
 * Builds the source of src/links.generated.ts from already-read link files.
 * `JSON.parse(...) as Link` is safe here — not just here-and-hoped — because every
 * caller of this function has already run `files` through validateLinkFiles(), which
 * checks the exact shape of `Link` (every required field present and typed, the slug
 * regex, no extra fields). generateLinks() below is the only production caller and
 * enforces that; this function stays separately testable on already-validated fixtures.
 */
export function generateLinksModule(files: LinkFile[]): string {
  const links: Record<string, Link> = {}
  for (const file of files) {
    const link = JSON.parse(file.content) as Link
    links[link.slug] = link
  }

  return (
    `// Generated by scripts/generate-links.ts from links/*.json. Do not edit by hand —\n`
    + `// this file is gitignored and rebuilt on every deploy (D3).\n`
    + `import type { Link } from './types.ts'\n\n`
    + `export const links: Record<string, Link> = ${JSON.stringify(links, null, 2)}\n`
  )
}

/**
 * Reads every link file in `sourceDir`, validates it against the documented schema
 * (the same check validate-links.ts's CI gate runs), and writes the generated module to
 * `outFile`. Refuses to write anything if a file fails validation, so a bad link file
 * can never reach the bundle even if this is run without the separate validation step.
 */
export function generateLinks(sourceDir: string, outFile: string): void {
  const files = readLinkFiles(sourceDir)

  const errors = validateLinkFiles(files)
  if (errors.length > 0) {
    throw new Error(
      `Refusing to generate ${outFile}: ${errors.length} problem(s) found in ${sourceDir}:\n${errors.join('\n')}`,
    )
  }

  writeFileSync(outFile, generateLinksModule(files))
}

function main() {
  const sourceDir = process.argv[2] ?? fileURLToPath(new URL('../links', import.meta.url))
  const outFile
    = process.argv[3] ?? fileURLToPath(new URL('../src/links.generated.ts', import.meta.url))
  generateLinks(sourceDir, outFile)
  console.log(`Generated ${outFile} from ${sourceDir}`)
}

if (import.meta.main)
  main()
